### ISSUE TITLE
Can I use your code?

### ISSUE THREAD

**Issue by thoslin** [alexmic/alexmic.github.com#1]
Hey Alex. I really dig your jekyll theme and I'd like to use it in my old jekyll site. But I found that you didn't specify a license in your repo. So can I use your code in my project? Thanks.

**Comment by alexmic** [comment]
Yes you can, but it would be cool if you attribute @orourkedesign :-)

**Comment by thoslin** [comment]
@alexmic Absolutely. I will attribute @orourkedesign in the footer as you did. Thank you so much!
